name: CI/CD Pipeline - Build and Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/re-shopping-cart-web-app
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: ./

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep "version = " build.gradle | sed "s/version = '//;s/'//")
          TIMESTAMP=$(date -u +"%Y%m%d_%H%M%S")
          echo "VERSION=${VERSION}_${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          load: true

      - name: Push Docker image to Hub
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep "version = " build.gradle | sed "s/version = '//;s/'//")
          TIMESTAMP=$(date -u +"%Y%m%d_%H%M%S")
          echo "VERSION=${VERSION}_${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Pull latest image and deploy
        run: |
          ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          # Pull the latest image
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Stop and remove old container
          docker stop re-shopping-cart || true
          docker rm re-shopping-cart || true

          # Run new container with production environment variables
          docker run -d \
            --name re-shopping-cart \
            --restart unless-stopped \
            -p 8080:8080 \
            --env-file /home/ec2-user/re-shopping-cart/.env.prod \
            -e SPRING_PROFILES_ACTIVE=prod \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          echo "Deployment completed successfully"
          EOF

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} "docker logs re-shopping-cart | tail -20"

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deploy_key
